Prevent running if nvidia modules not loadable

diff --git a/run_cosmic b/run_cosmic
--- a/run_cosmic
+++ b/run_cosmic
@@ -72,6 +72,15 @@ fi
 
 enable_all_cards
 
+`nvidia-smi >/dev/null 2>&1`
+DRIVER_LOADED="$?"
+
+if [[ $DRIVER_LOADED -gt 0 ]] ; then
+    echo "NVIDIA driver could not be loaded." 
+    exit
+fi
+
+
 if [[ $# -eq 0 ]] ; then
     # With no arguments, run on cosmic miner on all cards
     for i in $(seq 1 $NUM_CARDS) ; do
